"""add project ingest status

Revision ID: 162f30968c63
Revises: 83dc7f525f0b
Create Date: 2026-07-23 15:44:14.146785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '162f30968c63'
down_revision: Union[str, Sequence[str], None] = '83dc7f525f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('ingest_status', sa.String(length=20), nullable=False))
    op.add_column('projects', sa.Column('ingest_error', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('issue_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'issue_count')
    op.drop_column('projects', 'ingest_error')
    op.drop_column('projects', 'ingest_status')
    # ### end Alembic commands ###
