"""create core tables

Revision ID: 83dc7f525f0b
Revises: 
Create Date: 2026-07-23 13:34:12.423420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83dc7f525f0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_filename', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('raw_prompt', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('prompting_strategy', sa.String(length=50), nullable=False),
    sa.Column('effort', sa.String(length=20), nullable=True),
    sa.Column('grounding_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_query_logs_model', 'query_logs', ['model_id'], unique=False)
    op.create_index(op.f('ix_query_logs_project_id'), 'query_logs', ['project_id'], unique=False)
    op.create_index('ix_query_logs_strategy', 'query_logs', ['prompting_strategy'], unique=False)
    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_project_id'), 'sprints', ['project_id'], unique=False)
    op.create_index('ix_sprints_project_sequence', 'sprints', ['project_id', 'sequence'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_project_id'), 'anomalies', ['project_id'], unique=False)
    op.create_index('ix_anomalies_project_type', 'anomalies', ['project_id', 'anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomalies_sprint_id'), 'anomalies', ['sprint_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.Column('issue_key', sa.String(length=50), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assignee', sa.String(length=200), nullable=True),
    sa.Column('reporter', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('story_points', sa.Float(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('labels', sa.String(length=500), nullable=True),
    sa.Column('epic_link', sa.String(length=100), nullable=True),
    sa.Column('original_estimate', sa.Integer(), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_project_id'), 'issues', ['project_id'], unique=False)
    op.create_index('ix_issues_project_key', 'issues', ['project_id', 'issue_key'], unique=False)
    op.create_index('ix_issues_project_status', 'issues', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_issues_sprint_id'), 'issues', ['sprint_id'], unique=False)
    op.create_table('kpi_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kpi_project_metric', 'kpi_snapshots', ['project_id', 'metric'], unique=False)
    op.create_index(op.f('ix_kpi_snapshots_project_id'), 'kpi_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_kpi_snapshots_sprint_id'), 'kpi_snapshots', ['sprint_id'], unique=False)
    op.create_index('ix_kpi_sprint_metric', 'kpi_snapshots', ['sprint_id', 'metric'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('query_log_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('prompting_strategy', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_log_id'], ['query_logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_kpi_sprint_metric', table_name='kpi_snapshots')
    op.drop_index(op.f('ix_kpi_snapshots_sprint_id'), table_name='kpi_snapshots')
    op.drop_index(op.f('ix_kpi_snapshots_project_id'), table_name='kpi_snapshots')
    op.drop_index('ix_kpi_project_metric', table_name='kpi_snapshots')
    op.drop_table('kpi_snapshots')
    op.drop_index(op.f('ix_issues_sprint_id'), table_name='issues')
    op.drop_index('ix_issues_project_status', table_name='issues')
    op.drop_index('ix_issues_project_key', table_name='issues')
    op.drop_index(op.f('ix_issues_project_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_anomalies_sprint_id'), table_name='anomalies')
    op.drop_index('ix_anomalies_project_type', table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_project_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index('ix_sprints_project_sequence', table_name='sprints')
    op.drop_index(op.f('ix_sprints_project_id'), table_name='sprints')
    op.drop_table('sprints')
    op.drop_index('ix_query_logs_strategy', table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_project_id'), table_name='query_logs')
    op.drop_index('ix_query_logs_model', table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_table('projects')
    # ### end Alembic commands ###
